#!/usr/bin/env python3
import sys
import os

# Add the parent directory (share/<something>) so `gnostr` is on sys.path as a top-level package.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from main import main

if __name__ == '__main__':
    sys.exit(main(version="0.1.0"))
